name: Grass Bot

on:
  schedule:
    - cron: "0 0 * * *"  # 毎日1回（UTC）
  workflow_dispatch:  # 手動実行も可能

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update file
        run: |
          echo "update: $(date)" >> grass.txt

      - name: Commit changes
        run: |
          git config user.name "grass-bot"
          git config user.email "grass-bot@example.com"

          git add grass.txt

          git commit -m "chore: grow grass" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push
